- name: Copy new config
  hosts: all
  become: yes
  become_user: root
  tasks: 
    - name: Copy cgroups config
      copy:
        src: files/cgroup.conf
        dest: /etc/slurm/cgroup.conf

    - name: Copy slurm config
      template:
        src: files/slurm.conf
        dest: /etc/slurm/slurm.conf

- name: Get munge from master and restart
  hosts: master
  become: yes
  become_user: root
  tasks:
    - name: Fetch munge key
      fetch:
        src: /etc/munge/munge.key
        dest: files/munge.key
        flat: yes
        validate_checksum: yes

    - name: Restart slurmctld
      systemd:
        state: restarted
        name: slurmctld

- name: Copy munge to nodes copy gres and restart
  hosts: nodes 
  become: yes
  become_user: root
  tasks:
    - name: Copy topo file
      copy:
        src: files/inspur_topo_nccl_fix_qemu_orig.xml
        dest: /etc/inspur_topo_nccl_fix_qemu_orig.xml
    - name: Add new inspur_topo_nccl_fix_qemu_orig
      shell: echo "export NCCL_TOPO_FILE=/etc/inspur_topo_nccl_fix_qemu_orig.xml" | tee -a /home/slurm/.bashrc

    - name: Copy munge.key config to nodes
      copy:
        src: files/munge.key
        dest: /etc/munge/munge.key


    - name: Copy gres.conf to nodes
      copy:
        src: files/gres.conf
        dest: /etc/slurm/gres.conf

    - name: Restart slurmd
      systemd:
        state: restarted
        name: slurmd

    - name: Restart munge
      systemd:
        state: restarted
        name: munge
